GRANT CONNECT ON DATABASE bookstore TO bookstore_app_rw;
GRANT USAGE ON SCHEMA public TO bookstore_app_rw;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO bookstore_app_rw;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO bookstore_app_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO bookstore_app_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO bookstore_app_rw;